import { Vehicle, VehicleType, FuelType } from '@vehicle/vehicle.interface';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    manufacturer: 'Tesla',
    model: 'Model 3',
    year: 2022,
    type: VehicleType.ELECTRIC,
    price: 55000,
    fuelType: FuelType.ELECTRIC,
    transmission: 'Automatic',
    mileage: 15000,
    features: ['Autopilot', 'Long Range'],
    images: ['/images/tesla-model-3.jpg'],
    description: 'A premium electric sedan with cutting-edge technology.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    manufacturer: 'BMW',
    model: 'X5',
    year: 2021,
    type: VehicleType.SUV,
    price: 70000,
    fuelType: FuelType.GASOLINE,
    transmission: 'Automatic',
    mileage: 20000,
    features: ['All-wheel drive', 'Luxury Interior'],
    images: ['/images/bmw-x5.jpg'],
    description: 'A luxury SUV with superior performance and comfort.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    manufacturer: 'Toyota',
    model: 'Camry',
    year: 2020,
    type: VehicleType.SEDAN,
    price: 30000,
    fuelType: FuelType.HYBRID,
    transmission: 'Automatic',
    mileage: 30000,
    features: ['Fuel Efficiency', 'Spacious Interior'],
    images: ['/images/toyota-camry.jpg'],
    description: 'A reliable sedan with great fuel efficiency.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    manufacturer: 'Ford',
    model: 'F-150',
    year: 2023,
    type: VehicleType.TRUCK,
    price: 45000,
    fuelType: FuelType.GASOLINE,
    transmission: 'Automatic',
    mileage: 5000,
    features: ['Towing Capacity', 'Off-road Capabilities'],
    images: ['/images/ford-f150.jpg'],
    description: 'A powerful truck built for tough jobs.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    manufacturer: 'Porsche',
    model: '911',
    year: 2022,
    type: VehicleType.SPORTS,
    price: 120000,
    fuelType: FuelType.GASOLINE,
    transmission: 'Manual',
    mileage: 8000,
    features: ['High Performance', 'Luxury Design'],
    images: ['/images/porsche-911.jpg'],
    description: 'A high-performance sports car with luxury features.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    manufacturer: 'Mercedes-Benz',
    model: 'S-Class',
    year: 2021,
    type: VehicleType.LUXURY,
    price: 110000,
    fuelType: FuelType.DIESEL,
    transmission: 'Automatic',
    mileage: 25000,
    features: ['Luxury Interior', 'Advanced Safety Features'],
    images: ['/images/mercedes-s-class.jpg'],
    description: 'The pinnacle of luxury and advanced technology.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
