import { Vehicle, VehicleType, FuelType } from '@vehicle/vehicle.interface';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    manufacturer: 'Tesla',
    model: 'Model 3',
    year: 2022,
    type: VehicleType.ELECTRIC,
    price: 55000,
    fuelType: FuelType.ELECTRIC,
    transmission: 'Automatic',
    mileage: 15000,
    features: ['Autopilot', 'Long Range'],
    images: [
      'https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/Model-3-Choose-Performance-Desktop-LHD.png',
    ],
    description: 'A premium electric sedan with cutting-edge technology.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: '2',
    manufacturer: 'BMW',
    model: 'X5',
    year: 2021,
    type: VehicleType.SUV,
    price: 70000,
    fuelType: FuelType.GASOLINE,
    transmission: 'Automatic',
    mileage: 20000,
    features: ['All-wheel drive', 'Luxury Interior'],
    images: [
      'https://www.bmw.fr/content/dam/bmw/common/all-models/x-series/x5/2023/highlights/bmw-x-series-x5-sp-desktop.jpg',
    ],
    description: 'A luxury SUV with superior performance and comfort.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    manufacturer: 'Toyota',
    model: 'Camry',
    year: 2020,
    type: VehicleType.SEDAN,
    price: 30000,
    fuelType: FuelType.HYBRID,
    transmission: 'Automatic',
    mileage: 30000,
    features: ['Fuel Efficiency', 'Spacious Interior'],
    images: [
      'https://staticeu-h2.izmocars.com/toolkit/commonassets/2024/24toyota/24toyotacamryhevdesignsd8fbfr/24toyotacamryhevdesignsd8fbfr_pixGallery/_gallerypix/toyota_camryhevdesignsd8fbfr_angularfront.jpg',
    ],
    description: 'A reliable sedan with great fuel efficiency.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    manufacturer: 'Ford',
    model: 'F-150',
    year: 2023,
    type: VehicleType.TRUCK,
    price: 45000,
    fuelType: FuelType.GASOLINE,
    transmission: 'Automatic',
    mileage: 5000,
    features: ['Towing Capacity', 'Off-road Capabilities'],
    images: [
      'https://buildfoc.ford.com/dig/Ford/F-150%20F-150/2025/HD-FULL/Image%5B%7CFord%7CF-150%20F-150%7C2025%7C1%7C1.%7C801A.W1R.145.PUM.LSC.88R.89B.A56AC.A5GAA.63T.A7BAE.SS5.573.68L.924.435.B3NAB.BB7AD.168.BLBAF.BLDAC.BSBAC.BSHDF.BY1AM.BY3AB.CCAB.CFFAE.CLFGP.CLMHN.64B.T7R.DEEAB.AWD.998.67T.FMLAX.413.655.GRAAP.GTAAN.GTBAB.GTDAK.HJGAX.HKCBA.HTSAA.HUKAK.IBBAB.588.50M.IEVAQ.IGDAC.J3KAG.JASAC.59S.JCBAD.77R.44G.XL4.LTC.%5D/EXT/4/vehicle.png',
    ],
    description: 'A powerful truck built for tough jobs.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    manufacturer: 'Porsche',
    model: '911',
    year: 2022,
    type: VehicleType.SPORTS,
    price: 120000,
    fuelType: FuelType.GASOLINE,
    transmission: 'Manual',
    mileage: 8000,
    features: ['High Performance', 'Luxury Design'],
    images: [
      'https://assets.porsche.com/ca/quebec/-/media/Project/DealerWebsites/Canada/Quebec/Stage/Vehicules-neufs/911/stage-header-911-carrera-gts.jpg?rev=4c85161b1d1640808e53d6a240a389f3',
    ],
    description: 'A high-performance sports car with luxury features.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    manufacturer: 'Mercedes-Benz',
    model: 'S-Class',
    year: 2021,
    type: VehicleType.LUXURY,
    price: 110000,
    fuelType: FuelType.DIESEL,
    transmission: 'Automatic',
    mileage: 25000,
    features: ['Luxury Interior', 'Advanced Safety Features'],
    images: [
      'https://www.mercedes-benz.fr/content/france/fr/passengercars/models/saloon/s-class/overview/_jcr_content/root/responsivegrid/tabs/tabitem/hotspot_module/hotspot_simple_image.component.damq1.3457223568530.jpg/mercedes-benz-s-class-wv223-exterior-highlights-hotspot-start-3302x1858-08-2024.jpg',
    ],
    description: 'The pinnacle of luxury and advanced technology.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    manufacturer: 'Tesla',
    model: 'Model S',
    year: 2023,
    type: VehicleType.ELECTRIC,
    price: 79999,
    fuelType: FuelType.ELECTRIC,
    transmission: 'Automatic',
    mileage: 10000,
    features: ['Autopilot', 'Plaid Mode', 'Luxury Interior'],
    images: [
      'https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/Model-S-Performance-Desktop.jpg',
    ],
    description:
      'A luxury electric sedan with exceptional performance and cutting-edge technology.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    manufacturer: 'Tesla',
    model: 'Model X',
    year: 2022,
    type: VehicleType.ELECTRIC,
    price: 89999,
    fuelType: FuelType.ELECTRIC,
    transmission: 'Automatic',
    mileage: 8000,
    features: ['Falcon Wing Doors', 'All-Wheel Drive', 'Autopilot'],
    images: [
      'https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/Model-X-Performance-Desktop.jpg',
    ],
    description:
      'A high-performance electric SUV with stunning design and superior features.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    manufacturer: 'Tesla',
    model: 'Model Y',
    year: 2023,
    type: VehicleType.ELECTRIC,
    price: 58999,
    fuelType: FuelType.ELECTRIC,
    transmission: 'Automatic',
    mileage: 12000,
    features: ['Panoramic Roof', 'All-Wheel Drive', 'Autopilot'],
    images: [
      'https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/Model-Y-Range-Desktop-LHD-v2.jpg',
    ],
    description:
      'A versatile electric SUV offering great range and innovative features.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '10',
    manufacturer: 'Tesla',
    model: 'Cybertruck',
    year: 2023,
    type: VehicleType.TRUCK,
    price: 69999,
    fuelType: FuelType.ELECTRIC,
    transmission: 'Automatic',
    mileage: 5000,
    features: ['Bulletproof Glass', 'Tri-Motor AWD', 'Off-road Capabilities'],
    images: [
      'https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/Cybertruck-Second-Hero-Desktop.jpg',
    ],
    description:
      'An all-electric truck with futuristic design and extreme durability.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '11',
    manufacturer: 'Tesla',
    model: 'Roadster',
    year: 2023,
    type: VehicleType.SPORTS,
    price: 200000,
    fuelType: FuelType.ELECTRIC,
    transmission: 'Automatic',
    mileage: 2000,
    features: ['Top Speed of 250 mph', 'Luxury Design', 'All-Electric'],
    images: [
      'https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/Model-Y-Range-Desktop-LHD-v2.jpg',
    ],
    description:
      'A groundbreaking electric sports car with unparalleled performance.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
